import type { AboutContent } from './types'

export const aboutContentEn: AboutContent = {
  albums: [
    { title: 'Djent Is Not a Genre', type: 'Periphery', image: '/albums/periphery-v.webp' },
    { title: 'DATA', type: 'Tainy', image: '/albums/tainy-data.webp' },
    { title: 'Quest for Fire', type: 'Skrillex', image: '/albums/skrillex-quest.webp' },
    { title: 'To Pimp a Butterfly', type: 'Kendrick Lamar', image: '/albums/kendrick-tpab.jpg' },
    { title: 'The Life of Pablo', type: 'Kanye West', image: '/albums/kanye-tlop.jpg' },
    { title: 'Fauna', type: 'Haken', image: '/albums/haken-fauna.jpg' },
    { title: 'Alive 2007', type: 'Daft Punk', image: '/albums/daftpunk-alive.webp' },
    { title: 'Post Human: Nex Gen', type: 'Bring Me the Horizon', image: '/albums/bmth-nexgen.webp' },
    { title: 'All Eyez on Me', type: '2Pac', image: '/albums/2pac-alleyez.webp' },
    { title: 'Terraformer', type: 'Thank You Scientist', image: '/albums/tys-terraformer.jpg' },
    { title: 'Black Radio 2', type: 'Robert Glasper Experiment', image: '/albums/glasper-blackradio2.webp' },
    { title: 'Volition', type: 'Protest the Hero', image: '/albums/pth-volition.webp' },
    { title: 'Meteora', type: 'Linkin Park', image: '/albums/lp-meteora.webp' },
    { title: 'AM', type: 'Arctic Monkeys', image: '/albums/am-am.jpg' },
  ],
  experience: [
    {
      period: 'Feb 2026 - Present',
      title: 'Web Engineer',
      subtitle: 'Growth & Infrastructure',
      company: 'Atom',
      location: 'South Carolina, US (Remote)',
      highlights: [
        'Sole technical owner of the web marketing pipeline for a WhatsApp funnel automation SaaS across 14+ LATAM countries.',
        'Architected a token-first design system with custom npm packages: 1,865 tokens, 46 components, 4 frameworks, indexed for AI consumption via MCP server.',
        'Empowered non-technical growth teams to compose high-converting landing pages autonomously via Starlight docs and vibe-code snippets.',
        'Manage hybrid web infrastructure across Vercel and Cloudflare: DNS, rulesets, workers, CDN caching for Astro/Next.js and legacy stacks.',
      ],
    },
    {
      period: 'Dec 2025 - Present',
      title: 'Senior Web Platform Architect',
      subtitle: 'LATAM Regional Lead',
      company: 'ATFX',
      location: 'Mexico City (Hybrid)',
      highlights: [
        'Tech lead of the LATAM web pipeline: marketing sites, lead-gen funnels, email workflows, Salesforce integrations, and MCP skills.',
        'Architected ATFX Educacao, a Brazilian financial education SaaS, proposing Next.js + Supabase + Stripe over WordPress + WooCommerce.',
        'Design and maintain dual Figma design systems for 5 LATAM countries with tokens mirrored in code.',
        'Implement lead-gen and webinar funnels end-to-end: Figma flows, accessible HTML/CSS/JS, Power Automate, GA4 attribution, consent management.',
      ],
    },
    {
      period: 'Jun 2025 - Present',
      title: 'Founder & Lead Product/Design Engineer',
      subtitle: 'AI Automation & Web Systems',
      company: 'Draft Studio',
      location: 'Remote',
      highlights: [
        'Founded a remote creative studio with 5 specialists delivering AI-powered automation, scalable web platforms and e-commerce flows.',
        'Designed a zero-trust LLM architecture where AI acts purely as a reasoning engine with tool-calling.',
        'Built intelligent appointment systems integrating Google Calendar with automated proposal and booking flows.',
      ],
    },
    {
      period: 'Jul 2024 - Feb 2026',
      title: 'Full-Stack Developer & UX/UI Consultant',
      subtitle: 'AI Automation & Internal Tools',
      company: 'Aurin',
      location: 'Cuernavaca, MX',
      highlights: [
        'Engineered the Aurin.mx platform (Astro + AI chatbot) achieving 95+ Lighthouse score and <1.5s TTI.',
        'Built 8 production automation workflows processing 1,500+ monthly operations, reducing manual work by 25 hrs/week.',
        'Delivered a full-stack case-management system for a 292-attorney Chambers-ranked firm on Next.js, Supabase and Clerk.',
      ],
    },
    {
      period: 'Jul 2024 - Feb 2026',
      title: 'UX/UI Design Consultant',
      subtitle: 'Fintech & Banking Interfaces',
      company: 'Ancient Technologies',
      location: 'Austin, TX (Remote)',
      highlights: [
        'Led UX engineering for ancient.global, a marketing platform serving 15+ countries across LATAM, US and Europe.',
        'Architected a unified design system for 4 fintech products: 80+ reusable Figma components with comprehensive design tokens.',
        'Engineered a GPT-4 conversational chatbot with modular multi-assistant orchestration across 15+ service pages.',
      ],
    },
    {
      period: 'Apr - Nov 2024',
      title: 'UX/UI Designer & Frontend Developer',
      subtitle: 'E-commerce & Shopify',
      company: 'Spil Creative',
      location: 'Brooklyn, NY (Remote)',
      highlights: [
        'Designed and developed Shopify storefronts for Goslings Rum Bermuda, Health-Ade Kombucha and Leaders in Global Energy Insurance.',
        'Built custom Shopify templates using Liquid with flexible, brand-specific component architectures.',
      ],
    },
    {
      period: 'Apr - Nov 2023',
      title: 'Web Designer',
      subtitle: 'Wix Studio & Google Partnership',
      company: 'Zoek Marketing',
      location: 'San Francisco, CA (Remote)',
      highlights: [
        'Coordinated UX, design and development teams for website redesign projects across US clients.',
        'Translated Figma designs into production Wix Studio implementations with improved visual quality and responsiveness.',
      ],
    },
  ],
  volunteering: [
    {
      period: 'Oct 2024 - Present',
      title: 'Senior UX Designer',
      company: 'Athenis AI',
      label: 'Education',
      text: 'Design UX for an AI-powered e-learning platform with immersive 3D simulations, personalized learning paths, and real-time AI guidance.',
    },
    {
      period: 'Feb - Apr 2025',
      title: 'Frontend Developer',
      company: 'Opinator',
      label: 'CX Technology',
      text: 'Designed and implemented interactive, branded CX feedback interfaces (OPIs) for major clients across Europe and the Americas, working with the Madrid core team.',
    },
    {
      period: 'Apr - Oct 2024',
      title: 'Computer Science Teacher',
      company: 'Algorithmics Global',
      label: 'Education',
      text: 'Taught web design, Python, programming logic and digital literacy to 50+ students ages 6-17 through engaging, age-appropriate lessons.',
    },
    {
      period: 'Mar 2023 - May 2024',
      title: 'Software Engineer',
      company: 'CCyTEM',
      label: 'Social Impact',
      text: 'Programmed NAO robots with Python/C++ for 1,200+ students across 15+ underserved rural communities via the Science Trailer mobile outreach program.',
    },
  ],
  education: [
    'M.S. Software Engineering Management (UTEL, 2024)',
    'B.S. Computer Software Engineering (UTEL, 2023)',
    'AI Certificate (MIT via Santander Open Academy, 2024)',
    'IoT Certificate (MIT via Santander Open Academy, 2024)',
    'Data Science (BEDU + Microsoft + TecnolochicasPro)',
    'Film & Cinema Studies (UAM, 2022)',
    'Advanced English C1 (Platzi)',
    'Machine Learning with Python (Platzi, 2024)',
    'AWS & Azure Cloud Certifications (Platzi)',
    'Fullstack JS + React (Platzi)',
  ],
  stack: {
    'Product & Design': ['Figma', 'Figma AI', 'Design Tokens', 'Atomic Design', 'Radix UI', 'Shadcn/UI', 'WCAG 2.1 AA', 'Spline', 'Three.js'],
    Frontend: ['Next.js', 'React', 'Astro', 'TypeScript', 'Tailwind CSS', 'GSAP', 'Framer Motion', 'Zustand', 'Shopify Liquid'],
    'Marketing & Analytics': ['GA4', 'GTM', 'Salesforce', 'Resend', 'UTM', 'Conversion Tracking', 'Meta Ads', 'Google Ads', 'Power Automate'],
    'CMS & APIs': ['Payload', 'Strapi', 'Webflow', 'WordPress (headless)', 'GraphQL', 'REST', 'n8n', 'OpenAI API', 'Claude API'],
    Infrastructure: ['Vercel', 'Cloudflare', 'Supabase', 'PostgreSQL', 'Docker', 'Sentry', 'CI/CD', 'AWS', 'GCP'],
    'AI & Automation': ['MCP Servers', 'LLM Orchestration', 'n8n', 'Python', 'Tool-calling Agents'],
  },
}