import type { AboutContent } from './types'

export const aboutContentEs: AboutContent = {
  albums: [
    { title: 'Djent Is Not a Genre', type: 'Periphery', image: '/albums/periphery-v.webp' },
    { title: 'DATA', type: 'Tainy', image: '/albums/tainy-data.webp' },
    { title: 'Quest for Fire', type: 'Skrillex', image: '/albums/skrillex-quest.webp' },
    { title: 'To Pimp a Butterfly', type: 'Kendrick Lamar', image: '/albums/kendrick-tpab.jpg' },
    { title: 'The Life of Pablo', type: 'Kanye West', image: '/albums/kanye-tlop.jpg' },
    { title: 'Fauna', type: 'Haken', image: '/albums/haken-fauna.jpg' },
    { title: 'Alive 2007', type: 'Daft Punk', image: '/albums/daftpunk-alive.webp' },
    { title: 'Post Human: Nex Gen', type: 'Bring Me the Horizon', image: '/albums/bmth-nexgen.webp' },
    { title: 'All Eyez on Me', type: '2Pac', image: '/albums/2pac-alleyez.webp' },
    { title: 'Terraformer', type: 'Thank You Scientist', image: '/albums/tys-terraformer.jpg' },
    { title: 'Black Radio 2', type: 'Robert Glasper Experiment', image: '/albums/glasper-blackradio2.webp' },
    { title: 'Volition', type: 'Protest the Hero', image: '/albums/pth-volition.webp' },
    { title: 'Meteora', type: 'Linkin Park', image: '/albums/lp-meteora.webp' },
    { title: 'AM', type: 'Arctic Monkeys', image: '/albums/am-am.jpg' },
  ],
  experience: [
    {
      period: 'Feb 2026 - Presente',
      title: 'Web Engineer',
      subtitle: 'Growth e infraestructura',
      company: 'Atom',
      location: 'South Carolina, EE. UU. (Remoto)',
      highlights: [
        'Única responsable técnica del pipeline web de marketing para un SaaS de automatización de funnels en WhatsApp en 14+ países de LATAM.',
        'Arquitecté un design system token-first con paquetes npm propios: 1,865 tokens, 46 componentes, 4 frameworks, indexados para consumo por IA vía servidor MCP.',
        'Habilité a equipos de growth no técnicos para componer landing pages de alta conversión de forma autónoma con docs en Starlight y snippets vibe-code.',
        'Gestiono infraestructura web híbrida en Vercel y Cloudflare: DNS, rulesets, workers y caché CDN para Astro/Next.js y stacks legacy.',
      ],
    },
    {
      period: 'Dic 2025 - Presente',
      title: 'Senior Web Platform Architect',
      subtitle: 'Líder regional LATAM',
      company: 'ATFX',
      location: 'Ciudad de México (Híbrido)',
      highlights: [
        'Tech lead del pipeline web LATAM: sitios de marketing, funnels de leads, flujos de email, integraciones con Salesforce y skills MCP.',
        'Arquitecté ATFX Educacao, un SaaS de educación financiera en Brasil, proponiendo Next.js + Supabase + Stripe frente a WordPress + WooCommerce.',
        'Diseño y mantengo dos design systems en Figma para 5 países LATAM con tokens reflejados en código.',
        'Implemento funnels de leads y webinars end-to-end: flujos en Figma, HTML/CSS/JS accesible, Power Automate, atribución GA4 y gestión de consentimiento.',
      ],
    },
    {
      period: 'Jun 2025 - Presente',
      title: 'Founder & Lead Product/Design Engineer',
      subtitle: 'Automatización con IA y sistemas web',
      company: 'Draft Studio',
      location: 'Remoto',
      highlights: [
        'Fundé un estudio creativo remoto con 5 especialistas en automatización con IA, plataformas web escalables y flujos e-commerce.',
        'Diseñé una arquitectura LLM zero-trust donde la IA actúa solo como motor de razonamiento con tool-calling.',
        'Construí sistemas inteligentes de citas integrando Google Calendar con propuestas y reservas automatizadas.',
      ],
    },
    {
      period: 'Jul 2024 - Feb 2026',
      title: 'Full-Stack Developer & UX/UI Consultant',
      subtitle: 'Automatización con IA y herramientas internas',
      company: 'Aurin',
      location: 'Cuernavaca, MX',
      highlights: [
        'Desarrollé la plataforma Aurin.mx (Astro + chatbot con IA) con 95+ en Lighthouse y TTI <1.5s.',
        'Construí 8 flujos de automatización en producción que procesan 1,500+ operaciones al mes, reduciendo 25 h/semana de trabajo manual.',
        'Entregué un sistema full-stack de gestión de casos para un despacho de 292 abogados (Chambers) con Next.js, Supabase y Clerk.',
      ],
    },
    {
      period: 'Jul 2024 - Feb 2026',
      title: 'UX/UI Design Consultant',
      subtitle: 'Interfaces fintech y banca',
      company: 'Ancient Technologies',
      location: 'Austin, TX (Remoto)',
      highlights: [
        'Lideré UX engineering para ancient.global, plataforma de marketing en 15+ países de LATAM, EE. UU. y Europa.',
        'Arquitecté un design system unificado para 4 productos fintech: 80+ componentes reutilizables en Figma con design tokens completos.',
        'Desarrollé un chatbot conversacional GPT-4 con orquestación modular de asistentes en 15+ páginas de servicio.',
      ],
    },
    {
      period: 'Abr - Nov 2024',
      title: 'UX/UI Designer & Frontend Developer',
      subtitle: 'E-commerce y Shopify',
      company: 'Spil Creative',
      location: 'Brooklyn, NY (Remoto)',
      highlights: [
        'Diseñé y desarrollé tiendas Shopify para Goslings Rum Bermuda, Health-Ade Kombucha y Leaders in Global Energy Insurance.',
        'Construí plantillas Shopify en Liquid con arquitecturas de componentes flexibles y específicas por marca.',
      ],
    },
    {
      period: 'Abr - Nov 2023',
      title: 'Web Designer',
      subtitle: 'Wix Studio y alianza con Google',
      company: 'Zoek Marketing',
      location: 'San Francisco, CA (Remoto)',
      highlights: [
        'Coordiné equipos de UX, diseño y desarrollo en rediseños web para clientes en EE. UU.',
        'Traduje diseños de Figma a implementaciones en Wix Studio con mejor calidad visual y responsividad.',
      ],
    },
  ],
  volunteering: [
    {
      period: 'Oct 2024 - Presente',
      title: 'Senior UX Designer',
      company: 'Athenis AI',
      label: 'Educación',
      text: 'Diseño UX para una plataforma e-learning con IA, simulaciones 3D inmersivas, rutas de aprendizaje personalizadas y guía en tiempo real.',
    },
    {
      period: 'Feb - Abr 2025',
      title: 'Frontend Developer',
      company: 'Opinator',
      label: 'Tecnología CX',
      text: 'Diseñé e implementé interfaces interactivas de feedback CX (OPIs) para clientes en Europa y las Américas, con el equipo central en Madrid.',
    },
    {
      period: 'Abr - Oct 2024',
      title: 'Profesora de Ciencias de la Computación',
      company: 'Algorithmics Global',
      label: 'Educación',
      text: 'Enseñé diseño web, Python, lógica de programación y alfabetización digital a 50+ estudiantes de 6 a 17 años con lecciones adaptadas por edad.',
    },
    {
      period: 'Mar 2023 - May 2024',
      title: 'Software Engineer',
      company: 'CCyTEM',
      label: 'Impacto social',
      text: 'Programé robots NAO con Python/C++ para 1,200+ estudiantes en 15+ comunidades rurales vulnerables mediante el programa móvil Science Trailer.',
    },
  ],
  education: [
    'M.S. Software Engineering Management (UTEL, 2024)',
    'Lic. Ingeniería en Desarrollo de Software (UTEL, 2023)',
    'Certificado en IA (MIT vía Santander Open Academy, 2024)',
    'Certificado en IoT (MIT vía Santander Open Academy, 2024)',
    'Data Science (BEDU + Microsoft + TecnolochicasPro)',
    'Estudios de Cine (UAM, 2022)',
    'Inglés avanzado C1 (Platzi)',
    'Machine Learning con Python (Platzi, 2024)',
    'Certificaciones AWS y Azure Cloud (Platzi)',
    'Fullstack JS + React (Platzi)',
  ],
  stack: {
    'Producto y diseño': ['Figma', 'Figma AI', 'Design Tokens', 'Atomic Design', 'Radix UI', 'Shadcn/UI', 'WCAG 2.1 AA', 'Spline', 'Three.js'],
    Frontend: ['Next.js', 'React', 'Astro', 'TypeScript', 'Tailwind CSS', 'GSAP', 'Framer Motion', 'Zustand', 'Shopify Liquid'],
    'Marketing y analytics': ['GA4', 'GTM', 'Salesforce', 'Resend', 'UTM', 'Conversion Tracking', 'Meta Ads', 'Google Ads', 'Power Automate'],
    'CMS y APIs': ['Payload', 'Strapi', 'Webflow', 'WordPress (headless)', 'GraphQL', 'REST', 'n8n', 'OpenAI API', 'Claude API'],
    Infraestructura: ['Vercel', 'Cloudflare', 'Supabase', 'PostgreSQL', 'Docker', 'Sentry', 'CI/CD', 'AWS', 'GCP'],
    'IA y automatización': ['MCP Servers', 'LLM Orchestration', 'n8n', 'Python', 'Tool-calling Agents'],
  },
}